/**
 * Richard Cook Strategic Communications — supplied copy only.
 * Editorial additions are intentionally excluded; the visual system carries hierarchy.
 */
import { useEffect, useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { ArrowUpRight, Menu, X } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";

const nav = [
  { href: "/", label: "Home" },
  { href: "/brings", label: "What Richard Cook Brings" },
  { href: "/expertise", label: "Areas of Expertise" },
  { href: "/working-with-richard", label: "Working with Richard" },
  { href: "/integrating", label: "Integrating Strategy, Media and Reputation" },
  { href: "/case-studies", label: "Richard’s work – case studies" },
  { href: "/testimonials", label: "Testimonials" },
];

const cases = [
  { number: "01", title: "Crisis management — Fukushima nuclear accident (2011)", overview: "Richard worked with a well-established UK organisation with internationally recognised technical and regulatory expertise in the nuclear sector as it managed reputational and operational risks during and after the Fukushima nuclear accident.", detail: "The challenges were numerous and complex. The organisation needed to maintain its credibility as an authority on nuclear power while managing potential reputational risks arising from its longstanding professional connections in Japan. At the same time, it had to support staff and their families who remained in Japan after the disaster and might still be at risk. In parallel, the organisation had to ensure its fast-moving internal and external narratives remained in close alignment with messaging from the Japanese Government in Tokyo and the UK Government in London. Richard recognised that the response required a coordinated communications structure that could balance technical authority, reputational sensitivity and staff welfare while maintaining government alignment. He liaised closely with teams across the organisation over several months, in the UK, Japan and beyond, to establish clear lines of communication and consistent messaging. He helped position the organisation’s experts as trusted thought-leader voices who could contribute constructively to the public response, ensuring their technical insights were communicated credibly to multiple audiences. Richard’s work helped ensure the organisation maintained its credibility as a trusted authority throughout the crisis, with clear communications to staff, families, government stakeholders and the wider public." },
  { number: "02", title: "Crisis management — India (2008)", overview: "Richard worked for several months with a major global brand as it responded to serious and escalating allegations concerning resource mismanagement, contamination and pollution.", detail: "What began as a local issue rapidly developed into an international breaking-news story. Richard recognised that the organisation’s internal and external communications strategy and messaging had to be consistent, accurate and responsive. He managed this by working remotely at first and later from within India. Richard’s role included working across the highest levels of the organisation and with key specialist stakeholder groups to directly address the allegations. He also proactively engaged with media and government stakeholders. The organisation’s response contained the reputational risk, allowing it to maintain confidence and market share among key audiences. In due course, the relevant government authorities did not substantiate the allegations. Richard continued to work with the organisation for many years after the incident. The case demonstrated Richard’s ability to manage complex, fast-moving crisis communications across multiple stakeholders and geographies, combining remote coordination with on-the-ground engagement." },
  { number: "03", title: "Stakeholder communications — Pan-Asia (2005 - 2014)", overview: "Richard worked with a globally recognised consumer brand to relaunch stakeholder communications, initially with its regional senior management team and later with global leadership.", detail: "The challenge was to engage a geographically dispersed stakeholder group – that stretched from Japan to Pakistan – that was strategically influential and operationally important. Existing communications were functional but did not reflect the strength or distinctiveness of the brand. Richard recognised that the solution needed to reflect the brand’s distinctive positioning and rapidly growing presence across Asia. He oversaw the creation, launch and management of a print and digital publishing platform that replaced dry, overly internal communications with dynamic, design-led content that brought the brand’s positioning to life. Combining contemporary design with magazine and newsroom techniques, he developed a family of Asia-wide magazines and websites that were relevant, engaging and visually distinctive. By underpinning the platforms with strong editorial frameworks, Richard ensured the content was accurate, pertinent and rapidly updatable. This meant they could also function as effective media-relations tools and helped the company manage critical and crisis-related issues with greater consistency and control. The approach proved so effective that the company subsequently adopted the same model for its global internal and stakeholder communications. The relationship continued for almost a decade." },
  { number: "04", title: "Investor and regulatory relations — Hong Kong and UAE (2025)", overview: "Richard has a long-standing C-suite relationship with a Hong Kong- and UAE-based fintech and green investment firm, providing strategic support on communications, investor confidence and complex regulatory positioning.", detail: "Richard recognised that the firm needed coordinated strategic communications and investor-relations materials to support its regulatory licensing process and maintain investor confidence throughout. He worked closely with cross-jurisdictional legal, trading and administrative teams to ensure communications were clear, consistent and credible across multiple stakeholders. His work supported the firm’s successful application for in-principle approval from the Financial Services Regulatory Authority for a trading licence in Abu Dhabi Global Market (ADGM). Richard continues to work with the firm and maintains close, long-standing professional relationships with both founders." },
  { number: "05", title: "Media — news platform creation and launch (2020–2026)", overview: "Richard oversaw the design and build of a Hong Kong-based financial news platform to support its parent company’s mission: to simplify investor access to strategically important Asian New Economy markets.", detail: "The platform also supported the development of a sister platform creating indexes for areas such as ETF investment. Richard recognised that success required both editorial credibility and technical integration. Drawing on decades of experience in news media and search-engine optimisation, he assembled a geographically diverse team of journalists, multi-media editors, data specialists, commentators and analysts. Despite the significant operational and collaboration challenges created by the global Covid-19 lockdowns, Richard led the creation of this online news platform and virtual newsroom, with a targeted editorial focus on new economy and technology markets. Working with a specialist data team, he integrated its content with the sister index platform. Within two years of launch, the site had published almost 20,000 news articles and related multimedia content and was attracting an average of close to 500,000 page views a month. The project demonstrated Richard’s ability to combine editorial judgement, technical integration and team leadership to build a credible and highly visible media platform under challenging operational conditions." },
  { number: "06", title: "Stakeholder and investor relations — Global logistics conglomerate (2009–2010)", overview: "Richard worked for more than a year with a high-profile Japanese logistics conglomerate to create a compelling multimedia project that demonstrated the organisation’s integrated global capabilities.", detail: "The challenge was to correct a legacy customer perception that the organisation’s shipping, rail, trucking, warehouse and distribution functions were managed by separate businesses. In reality, the conglomerate operated a unified, end-to-end logistics network. Richard recognised that a conventional corporate communications campaign would struggle to overcome this perception. His solution was to document the real journey of a single shipping container as it travelled 125,000 kilometres carrying different cargo across five continents and demonstrating how the organisation’s various integrated logistics and transportation functions worked together. Richard successfully pitched the project at board level in Tokyo and then travelled with the production team to manage the multimedia documentary that followed the container’s global journey. The project received strong industry recognition; one shipping correspondent described it as a project that “defined the age we live in.” The project subsequently became the basis for a major mainstream media documentary led by the BBC, extending its reach far beyond the organisation’s immediate stakeholder audience. The work demonstrated how experiential storytelling can correct complex customer misconceptions while also repositioning a global brand’s capabilities." },
  { number: "07", title: "International stakeholder and cultural relations — Italy and China (2008)", overview: "Richard worked with an Italian municipal authority following the city’s hosting of the Winter Olympics to create a distinctive multimedia project: a coffee-table book and travelling photography exhibition.", detail: "The authority wanted a project that showcased the region, its culture and its people. Richard recognised that the opportunity extended beyond commemoration: there was a strategic need to create a lasting record that not only beyond celebrating the city’s Olympic role while also supporting the authority’s international relationship-building objectives, particularly with the next Asian host city. Richard devised, developed and delivered the project over more than two years. The book and exhibition were subsequently used by the municipal authority at governmental, Olympic, cultural and trade events, providing a distinctive platform for cultural diplomacy and relationship-building between Italy and Asia. The project led to lasting professional connections in Italy, and the municipal authority invited Richard to continue working with it on further premium Italy–Asia projects. The work demonstrated how cultural assets can be leveraged to support international stakeholder relations and institutional positioning." },
];

const testimonials = [
  { name: "Dr Christian Kronseder", role: "CEO, ALLINDEX", note: "Custom indexing and thematic portfolio construction", quote: "I have worked closely with Richard for more than five years and he excels at translating complex, index-based themes into clear, compelling narratives that can be widely understood. Another notable attribute is his ability to build, manage and motivate teams. His leadership and balancing of multi-skilled editorial and data teams has made the complex task of combining thematic index portfolios with media content as straightforward as it can be." },
  { name: "Louis Benito", role: "Innovation and Co-creation Director, Lloyd’s Register Asia", note: "", quote: "Richard is a skilled communications professional who has a talent for integrating media engagement with group vision and clever strategic internal and external events. He’s a great person to work with, and I would welcome the opportunity to do so again." },
  { name: "Robert Swan OBE", role: "Explorer and Founder, 2041 Foundation", note: "First person in history to walk to both the South Pole and the North Pole", quote: "Richard Cook has been a good friend to the 2041 Foundation. He’s helped significantly for many years with media liaison in Asia and with fundraiser engagement. He also came to Antarctica with us where he was a great and enthusiastic team member and also gave very good media training to expedition participants." },
  { name: "David Cox", role: "Coca-Cola Asia Communications Director", note: "", quote: "Richard is very good at what he does. He knows media and news methodologies very well and how to engagingly and strategically embed that into corporate narratives. His skills and judgment have proved invaluable to us." },
];

function Logo() { return <Link href="/" className="brand" aria-label="Richard Cook Strategic Communications home"><span className="brand-mark" aria-hidden="true" /><span className="brand-copy"><strong>RICHARD COOK</strong><small>STRATEGIC COMMUNICATIONS</small></span></Link>; }

function Layout({ children }: { children: React.ReactNode }) {
  const [location] = useLocation();
  const [open, setOpen] = useState(false);
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: "instant" as ScrollBehavior }); setOpen(false); }, [location]);
  return <div className="site-shell"><header className="site-header"><Logo /><button className="menu-button" aria-label={open ? "Close navigation" : "Open navigation"} onClick={() => setOpen(!open)}>{open ? <X size={21} /> : <Menu size={21} />}<span>Menu</span></button><nav className={open ? "site-nav is-open" : "site-nav"} aria-label="Primary navigation">{nav.map((item, index) => <Link key={item.href} href={item.href} className={location === item.href ? "nav-link active" : "nav-link"}><span className="nav-number">0{index + 1}</span>{item.label}</Link>)}</nav></header><main key={location} className="page-main">{children}</main><footer className="site-footer"><div><Logo /></div><div className="footer-links"><span className="eyebrow" aria-hidden="true" />{nav.map((item, index) => <Link key={item.href} href={item.href}><span className="footer-number">0{index + 1}</span>{item.label}</Link>)}</div><div className="footer-contact"><span className="eyebrow">Arrange a confidential conversation</span><a href="mailto:hello@richardcook.uk" className="text-link">hello@richardcook.uk <ArrowUpRight size={15} /></a></div></footer></div>;
}

function PageIntro({ index, title, intro }: { index: string; title: string; intro?: string }) { return <section className={index ? "page-intro" : "page-intro page-intro-utility"}><div className="intro-index">{index}</div><div><h1>{title}</h1>{intro && <p className="intro-copy">{intro}</p>}</div></section>; }
function CTA({ children = "Arrange a confidential conversation" }: { children?: React.ReactNode }) { return <a href="mailto:hello@richardcook.uk" className="cta"><span>{children}</span><ArrowUpRight size={17} /></a>; }
function TextList({ items }: { items: string[] }) { return <ul className="text-list">{items.map((item) => <li key={item}><span className="list-mark">•</span><span>{item}</span></li>)}</ul>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="split-section"><div className="section-label" /><div><h2>{title}</h2><div className="section-body">{children}</div></div></section>; }

function Home() { return <section className="home-page"><section className="hero hero-without-art"><div className="hero-copy"><h1>Richard Cook<br /><em>Strategic Communications</em></h1><p className="hero-sub">Clear, credible strategic communications, media counsel and crisis response</p><p className="hero-body">Richard Cook provides strategic communications, media strategy and crisis counsel to leaders and organisations facing complexity, scrutiny or change.</p><p className="hero-body">His work brings together three decades of international experience across brands, newsrooms and high-stakes reputation management.</p><p className="hero-body">Richard helps leaders and organisations:</p><TextList items={["Understand how they are perceived.", "Prioritise the communications that matter most – internally and publicly.", "Act credibly when circumstances are complex or stakes are high."]} /><p className="hero-body">Richard has worked extensively with global consumer brands, technical and regulatory authorities, index and data businesses, environmental and carbon platforms, expeditions, fintech and investment firms, logistics and transportation conglomerates, and media and news platforms.</p><p className="hero-body">Richard has worked globally and is now based in North Yorkshire. He typically works on long-term and retainer assignments but is also available for undertake advisory projects.</p><p className="hero-body">He is available for crisis response, strategic communications reviews, and media platform development. All enquiries are welcome.</p><CTA /></div></section></section>; }

function Brings() { return <><PageIntro index="01" title="What Richard Cook brings" intro="Complex organisational communications rarely belong to a single discipline." /><Section title="Brand, media, stakeholder expectations, leadership behaviour and operational realities are closely connected."><p>Richard’s experience and work brings these perspectives together:</p><TextList items={["Strategic communications – aligning communications with organisational purpose and commercial priorities.", "Brand and reputation – clarifying positioning and strengthening credibility.", "Newsroom and media insight – testing whether narratives and claims withstand scrutiny.", "International judgement – honing communications across markets, cultures and regulatory environments.", "Crisis response – helping leadership teams prepare, plan and communicate under pressure."]} /><p>This integrated approach better equips organisations to think clearly, align effectively and act credibly – strategically and operationally.</p><p>In an increasingly volatile, scrutinised and competitive world, Richard Cook works with leaders and organisations to turn complexity into clarity, align communications with action and retain the credibility needed to earn trust and succeed.</p></Section></>; }

function Expertise() { return <><PageIntro index="02" title="Richard’s areas of expertise" /><Section title="Richard advises on:"><TextList items={["Reputation and positioning.", "Executive voice and visibility.", "Media, investor and stakeholder strategy.", "Crisis preparedness and response.", "International communications.", "High-stakes announcements, change and reputational challenges."]} /></Section><Section title="Who he works with"><TextList items={["Founder-led companies entering a more visible phase.", "International businesses expanding into unfamiliar markets.", "Regulated or politically-exposed organisations.", "Technology and fintech companies with complex narratives and propositions.", "Professional-services firms seeking to turn internal expertise into stronger public thought-leadership authority", "Organisations facing controversy, investigation, restructuring or leadership transition.", "Corporate affairs teams seeking discreet, senior white-label counsel on complex, high-stakes assignments.", "Boards and executive teams without sufficient specialist communications capacity"]} /></Section></>; }

function Working() { return <><PageIntro index="03" title="Working With Richard Cook" /><Section title="Richard works with a wide-ranging list of companies, organisations and governments in a variety of long term projects and retainers and also can work on day-level engagements."><p>To best start engagement, Richard offers focused one-day intro sessions that can include:</p><p>For organisations seeking senior advice before committing to a broader programme.</p><div className="session-grid">{[{t:"One-Day Communications Diagnostic",b:"Identify the communications issue creating the greatest strategic or reputational drag – to establish the priorities for addressing it."},{t:"Newsroom Test",b:"Put your narrative, claims and spokespeople under informed journalistic pressure before any real conversation begin."},{t:"Reputational Readiness Session",b:"Test leadership assumptions, identify pressure points and clarify what needs to happen before an issue becomes a crisis."}].map((s) => <article className="session" key={s.t}><h3>{s.t}</h3><p>{s.b}</p></article>)}</div><p>Each session is confidential, senior-led and fixed-scope, with practical decisions and clear next steps as outputs.</p><CTA>Discuss a confidential session</CTA></Section></>; }

function Integrating() { return <><PageIntro index="04" title="Integrating strategy, media and reputation" /><Section title="Richard Cook’s career has won awards and crossed geographies, sectors and communications disciplines."><p>One common thread has been helping organisations and leaders make sense of complexity, communicate with authority and protect credibility when the stakes are high.</p><p>His experience includes advising senior leaders, public institutions and major international companies on sensitive issues spanning communications, media, reputation and crisis management.</p><p>Richard lived and worked in Asia for more than 20 years, operating across complex markets and international, regulated environments.</p><p>He and his family are now based in North Yorkshire, while his work remains international in outlook and reach.</p><p>His varied experience has consolidated into one coherent professional capability: integrating strategic, editorial, brand, international and crisis judgement to understand complex communications challenges and help organisations address them credibly.</p><p>He works independently and discreetly, either directly with leaders and organisations or alongside corporate affairs teams requiring additional senior counsel.</p><div className="inline-actions"><Link href="/case-studies" className="text-link">Read selected experience <ArrowUpRight size={15} /></Link><a href="https://www.linkedin.com" className="text-link" target="_blank" rel="noreferrer">Connect on LinkedIn <ArrowUpRight size={15} /></a></div></Section><section className="dark-cta"><h2>Facing a communications, reputation or media challenge? Arrange a confidential conversation with Richard.</h2><CTA /></section></>; }

function CaseStudies() { return <><PageIntro index="05" title="Richard’s work – case study overviews" intro="The following case studies illustrate the range and nature of Richard’s work across strategic communications, crisis response, media, stakeholder engagement and international relations." /><section className="case-intro"><p>To respect client confidentiality, names are withheld in selected cases. The examples are not exhaustive; Richard also undertakes ongoing assignments that are not detailed here.</p></section><section className="case-list">{cases.map((item) => <article className="case-row" key={item.number}><div className="case-number">{item.number}</div><div className="case-main"><h2>{item.title}</h2><p>{item.overview}</p><div className="case-detail"><p>{item.detail}</p></div></div></article>)}</section></>; }

function Testimonials() { return <><PageIntro index="07" title="Testimonials" /><section className="testimonial-list">{testimonials.map((item, i) => <figure className="testimonial" key={item.name}><div className="quote-mark">“</div><blockquote>{item.quote}”</blockquote><figcaption><strong>{item.name}</strong><span>{item.role}</span>{item.note && <small>{item.note}</small>}</figcaption><div className="testimonial-index">0{i + 1}</div></figure>)}</section></>; }

function Contact() { return <><PageIntro index="" title="Arrange a confidential conversation" /><section className="contact-section"><div><h2>All enquiries are welcome.</h2><p>hello@richardcook.uk</p><a className="cta" href="mailto:hello@richardcook.uk"><span>Arrange a confidential conversation</span><ArrowUpRight size={17} /></a></div></section></>; }
function NotFound() { return <section className="not-found"><h1>Page not found.</h1><Link href="/" className="text-link">Return home <ArrowUpRight size={15} /></Link></section>; }
function Router() { return <Switch><Route path="/" component={Home} /><Route path="/brings" component={Brings} /><Route path="/expertise" component={Expertise} /><Route path="/working-with-richard" component={Working} /><Route path="/integrating" component={Integrating} /><Route path="/case-studies" component={CaseStudies} /><Route path="/testimonials" component={Testimonials} /><Route path="/contact" component={Contact} /><Route component={NotFound} /></Switch>; }
export default function App() { return <ErrorBoundary><ThemeProvider defaultTheme="light"><TooltipProvider><Toaster /><Layout><Router /></Layout></TooltipProvider></ThemeProvider></ErrorBoundary>; }
